"""
Django settings for Backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Load environment variables
load_dotenv()

# from django.contrib import admin

# admin.site.site_header = "Fusion Admin"
# admin.site.site_title = "Fusion Control Panel"
# admin.site.index_title = "Dashboard"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Custom
    'rest_framework',
    "corsheaders",
    'ckeditor',
    'About',
    'Blog',
    'Home',
    'Service',
    'Contact',
    
]

# CKEDITOR SETTINGS
CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "Custom",
        "toolbar_Custom": [

            # Text styles
            ["Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript"],

            # Font controls
            ["Font", "FontSize", "TextColor", "BGColor"],

            # Paragraph formatting
            ["Format", "Styles"],

            # Alignment
            ["JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"],

            # Lists
            ["NumberedList", "BulletedList", "Outdent", "Indent"],

            # Links
            ["Link", "Unlink", "Anchor"],

            # Insert content
            ["Image", "Table", "HorizontalRule", "SpecialChar"],

            # Clipboard
            ["Cut", "Copy", "Paste", "PasteText", "PasteFromWord"],

            # Undo / Redo
            ["Undo", "Redo"],

            # Cleanup
            ["RemoveFormat"],

            # Tools
            ["Maximize", "ShowBlocks", "Source"],
        ],
    }
}

MIDDLEWARE = [
    # Custom
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    # Custom ends here
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

ROOT_URLCONF = 'Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Django Secret Key
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')

# EMIAL CONFIGURATIONS
MAIL_BACKEND= os.environ.get('MAIL_BACKEND', '')
EMAIL_HOST= os.environ.get('EMAIL_HOST', '')
EMAIL_USE_TLS= os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_PORT= int(os.environ.get('EMAIL_PORT', '547'))
EMAIL_HOST_USER=os.environ.get('EMAIL_HOST_USER', 'info.oforitechsolutions@gmail.com')
EMAIL_HOST_PASSWORD=os.environ.get('EMAIL_HOST_PASSWORD', '')

# Company Info
COMPANY_NAME = os.getenv('COMPANY_NAME', 'OFORITECH SOLUTIONS')
COMPANY_EMAIL = os.getenv('COMPANY_EMAIL', 'info.oforitechsolutions@gmail.com')
COMPANY_PHONE = os.getenv('COMPANY_PHONE', '')
COMPANY_ADDRESS = os.getenv('COMPANY_ADDRESS', '')
COMPANY_WEBSITE = os.getenv('COMPANY_WEBSITE', 'https://oforitechsolutions.com')

# Increase request timeout
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
