"""
Django settings for Backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Load environment variables
load_dotenv()

# from django.contrib import admin

# admin.site.site_header = "Fusion Admin"
# admin.site.site_title = "Fusion Control Panel"
# admin.site.index_title = "Dashboard"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Django Secret Key
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Render automatically sets RENDER_EXTERNAL_HOSTNAME
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')

# Initialize ALLOWED_HOSTS
ALLOWED_HOSTS = []

# Add Render hostname if available
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Also add your custom domain if you have one
CUSTOM_DOMAIN = os.environ.get('CUSTOM_DOMAIN')
if CUSTOM_DOMAIN:
    ALLOWED_HOSTS.append(CUSTOM_DOMAIN)

# For development/local
if DEBUG:
    ALLOWED_HOSTS.extend(['localhost', '127.0.0.1', '[::1]'])
else:
    # In production, also allow Render's service name without .onrender.com
    if RENDER_EXTERNAL_HOSTNAME:
        service_name = RENDER_EXTERNAL_HOSTNAME.replace('.onrender.com', '')
        ALLOWED_HOSTS.append(service_name)

# ALLOWED_HOSTS = ['companyapi-k2mx.onrender.com', ]


# Application definition

INSTALLED_APPS = [
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Custom
    'rest_framework',
    "corsheaders",
    'ckeditor',
    'About',
    'Blog',
    'Home',
    'Service',
    'Contact',
    
]

# CKEDITOR SETTINGS
CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "Custom",
        "toolbar_Custom": [

            # Text styles
            ["Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript"],

            # Font controls
            ["Font", "FontSize", "TextColor", "BGColor"],

            # Paragraph formatting
            ["Format", "Styles"],

            # Alignment
            ["JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"],

            # Lists
            ["NumberedList", "BulletedList", "Outdent", "Indent"],

            # Links
            ["Link", "Unlink", "Anchor"],

            # Insert content
            ["Image", "Table", "HorizontalRule", "SpecialChar"],

            # Clipboard
            ["Cut", "Copy", "Paste", "PasteText", "PasteFromWord"],

            # Undo / Redo
            ["Undo", "Redo"],

            # Cleanup
            ["RemoveFormat"],

            # Tools
            ["Maximize", "ShowBlocks", "Source"],
        ],
    }
}

MIDDLEWARE = [
    # Custom
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",

    # Custom ends here
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://oforitech-solution-frontend.vercel.app",
    "https://oforitech-solutions.vercel.app",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

ROOT_URLCONF = 'Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# ----------STATIC FILES--------------------------

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =========== WHITENOISE CONFIGURATION ===========
# Add this AFTER the static files section above

# Only use WhiteNoise in production (when DEBUG=False)
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    
    # Optional optimizations
    WHITENOISE_MAX_AGE = 31536000  # Cache for 1 year
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_MANIFEST_STRICT = False



# EMIAL CONFIGURATIONS
# =========== EMAIL CONFIGURATION ===========
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  
# SERVER_EMAIL = EMAIL_HOST_USER 

# COMPANY_EMAIL = os.environ.get('COMPANY_EMAIL', EMAIL_HOST_USER)

# Add Resend configuration:
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
EMAIL_BACKEND = 'Contact.resend_backend.ResendBackend'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'oforitechsolutions@gmail.com')
COMPANY_EMAIL = os.environ.get('COMPANY_EMAIL', DEFAULT_FROM_EMAIL)

# Optional: Add your company info
COMPANY_NAME = os.getenv('COMPANY_NAME', 'OFORITECH SOLUTIONS')
COMPANY_PHONE = os.getenv('COMPANY_PHONE', '')
COMPANY_WEBSITE = os.getenv('COMPANY_WEBSITE', 'https://oforitechsolutions.com')

# Company Info
# COMPANY_NAME = os.getenv('COMPANY_NAME', 'OFORITECH SOLUTIONS')
# COMPANY_PHONE = os.getenv('COMPANY_PHONE', '')
# COMPANY_ADDRESS = os.getenv('COMPANY_ADDRESS', '')
# COMPANY_WEBSITE = os.getenv('COMPANY_WEBSITE', 'https://oforitechsolutions.com')

# Increase request timeout
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
