# Generated by Django 6.0.1 on 2026-01-22 19:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_category', models.CharField(max_length=255)),
                ('blog_name', models.CharField(max_length=255)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='featuredblogs/')),
            ],
        ),
    ]
