# Generated by Django 6.0.1 on 2026-01-23 12:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=225)),
                ('service_description', ckeditor.fields.RichTextField()),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service/')),
            ],
        ),
        migrations.CreateModel(
            name='TopClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='topclient/')),
            ],
        ),
    ]
