# Generated by Django 6.0.1 on 2026-01-23 12:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225)),
                ('job_title', models.CharField(blank=True, max_length=225)),
                ('image', models.ImageField(blank=True, null=True, upload_to='devteam/')),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=225)),
                ('founder_title', models.CharField(max_length=225)),
                ('founder_story', ckeditor.fields.RichTextField()),
                ('founder_image', models.ImageField(blank=True, null=True, upload_to='founder/')),
            ],
        ),
        migrations.CreateModel(
            name='TrustedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
